### ISSUE TITLE
requires sudo

### ISSUE THREAD

**Issue by goetzk** [wtanaka/ansible-role-virtualenv#11]
Hi,
just an FYI - you're assuming sudo is available but it isn't necessary  installed on all your supported platforms. You should note it is a dependency in your meta, readme or install it before running.

thanks,!

**Comment by goetzk** [comment]
btw,  franklinkim.sudo is a good sudo role if you would like a suggestion.

**Comment by wtanaka** [comment]
@goetzk thanks for the info; do you happen to know which platforms?  Also; when this use case occurs for you, do you find that you are exposing a root login directly over ssh, and having ansible log in as root?  Or do you find that you are running a bootstrap in your playbook prior to running ansible anyway?

**Comment by goetzk** [comment]
Hi,
After experimenting a bit more I think its probably a bug in my setup (I changed a few things and have had no further problems.)
I'm going to close this on the assumption it was me being ... wrong :)
thanks,
